name: Deploy POC MyWealth UI to AWS Elastic Beanstalk

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Install zip
        run: sudo apt-get install -y zip

      - name: Generate version label
        id: version
        run: echo "VERSION=build-$(date +%s)" >> $GITHUB_ENV

      - name: Zip application
        run: zip -r deploy.zip . -x "*.git*" "node_modules/*" "dist/*" "*.log" ".vscode/*" ".idea/*" "*.md"

      - name: Upload to S3
        run: |
          S3_KEY="deploy-${VERSION}.zip"
          echo "S3_KEY=$S3_KEY" >> $GITHUB_ENV
          aws s3 cp deploy.zip s3://elasticbeanstalk-ca-central-1-682740202133/$S3_KEY

      - name: Create EB application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name "demo-mywealth-ui" \
            --version-label "$VERSION" \
            --source-bundle S3Bucket="elasticbeanstalk-ca-central-1-682740202133",S3Key="$S3_KEY"

      - name: Deploy to EB environment
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name "Demo-mywealth-ui-env" \
            --version-label "$VERSION"
